# Generated by Django 3.2.3 on 2021-10-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20211010_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('date_created', models.DateTimeField()),
                ('result', models.CharField(max_length=20)),
            ],
        ),
    ]
