# Generated by Django 3.2.3 on 2021-10-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_image_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_Vehicle',
        ),
    ]
